name: CI

on:
 push:
   branches: [main]
   
jobs:
  CI:
    runs-on: windowns-pro
    
    steps:
       - name: Docker Login
         uses: docker/login-action@v3
         with:
            username: ${{secrets.USER}}
            password: ${{secrets.PASSWORD}}
            
       - name: Build and push Docker images
         uses: docker/build-push-action@v4.0.0
         with:
          context: .
          file: .
          push: true
          tags:
             Laravel:v1
             Laravel:latest

           
      
   
   
   
